version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: soniataran79@gmail.com
      GIT_NAME: aman25502
      VERSION: 2.2
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget
           git clone https://github.com/aman25502/misaka-kernel-msm8937-4.9 -b ci-branch kernel
           cd kernel
           bash unified.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
